const fs = require('fs');

let data = fs.readFileSync('src/data/oarConstraintsData.ts', 'utf-8');

const newItems = `
  // === HEAD & NECK (HYPOFRACTIONATION) ===
  {
    id: 'hn-spinal-cord-hypo',
    organ: 'Spinal Kord (Spinal Cord)',
    region: 'bas-boyun',
    fractionation: 'hipofraksiyon',
    metric: 'Dmax',
    limit: 'Dmax < 25-30 Gy (EQD2 < 45-50 Gy)',
    endpoint: 'Miyelopati (Myelopathy)',
    priority: 'hard',
    alphaBeta: 2,
    source: 'QUANTEC / UK Guidelines',
    context: '10-15 fx palyatif / quad shot.',
  },
  {
    id: 'hn-brainstem-hypo',
    organ: 'Beyin Sapı (Brainstem)',
    region: 'bas-boyun',
    fractionation: 'hipofraksiyon',
    metric: 'Dmax',
    limit: 'Dmax < 35-40 Gy',
    endpoint: 'Beyin sapı nekrozu / Kranial nöropati',
    priority: 'hard',
    alphaBeta: 2,
    source: 'Clinical Guidelines',
    context: '',
  },
  {
    id: 'hn-carotid-hypo',
    organ: 'Karotis Arter (Carotid Artery)',
    region: 'bas-boyun',
    fractionation: 'hipofraksiyon',
    metric: 'Dmax',
    limit: 'Dmax < 35-40 Gy',
    endpoint: 'Karotis rüptürü (Carotid blowout syndrome)',
    priority: 'hard',
    alphaBeta: 3,
    source: 'Clinical Guidelines',
    context: 'Özellikle yeniden ışınlamada (re-irradiation) kritik.',
  },
  {
    id: 'hn-mandible-hypo',
    organ: 'Mandibula',
    region: 'bas-boyun',
    fractionation: 'hipofraksiyon',
    metric: 'Dmax',
    limit: 'Dmax < 40-45 Gy',
    endpoint: 'Osteoradyonekroz (ORN)',
    priority: 'soft',
    alphaBeta: 3,
    source: 'Clinical Guidelines',
    context: '',
  },
  {
    id: 'hn-larynx-hypo',
    organ: 'Larenks (Larynx)',
    region: 'bas-boyun',
    fractionation: 'hipofraksiyon',
    metric: 'Mean & Dmax',
    limit: 'Mean < 25-30 Gy; Dmax < 40 Gy',
    endpoint: 'Larengeal ödem / nekroz',
    priority: 'soft',
    alphaBeta: 3,
    source: 'Clinical Guidelines',
    context: '',
  },
  {
    id: 'hn-pharynx-hypo',
    organ: 'Faringeal Konstriktörler / Servikal Özofagus',
    region: 'bas-boyun',
    fractionation: 'hipofraksiyon',
    metric: 'Mean',
    limit: 'Mean < 30-35 Gy',
    endpoint: 'Ciddi disfaji / striktür',
    priority: 'soft',
    alphaBeta: 3,
    source: 'Clinical Guidelines',
    context: '',
  },
  {
    id: 'hn-parotid-hypo',
    organ: 'Parotis Bezi',
    region: 'bas-boyun',
    fractionation: 'hipofraksiyon',
    metric: 'Mean',
    limit: 'Mean < 20-22 Gy',
    endpoint: 'Ciddi kserostomi',
    priority: 'soft',
    alphaBeta: 3,
    source: 'Clinical Guidelines',
    context: '',
  },
  {
    id: 'hn-brachial-hypo',
    organ: 'Brakial Pleksus',
    region: 'bas-boyun',
    fractionation: 'hipofraksiyon',
    metric: 'Dmax',
    limit: 'Dmax < 35-40 Gy',
    endpoint: 'Pleksopati',
    priority: 'soft',
    alphaBeta: 2,
    source: 'Clinical Guidelines',
    context: '',
  },

  // === HEAD & NECK (SBRT 3-5 fx) ===
  // Carotid Artery
  {
    id: 'hn-carotid-sbrt-3fx',
    organ: 'Karotis Arter (Carotid Artery)',
    region: 'bas-boyun',
    fractionation: 'sbrt-3fx',
    metric: 'Dmax',
    limit: 'Dmax < 27-30 Gy',
    endpoint: 'Karotis rüptürü (CBS)',
    priority: 'hard',
    alphaBeta: 3,
    source: 'MSKCC / HyTEC',
    context: 'Yeniden ışınlamada >180 derece sarmasından kaçının.',
  },
  {
    id: 'hn-carotid-sbrt-5fx',
    organ: 'Karotis Arter (Carotid Artery)',
    region: 'bas-boyun',
    fractionation: 'sbrt-5fx',
    metric: 'Dmax & V35Gy',
    limit: 'Dmax < 40 Gy; V35Gy < 1 cc',
    endpoint: 'Karotis rüptürü (CBS)',
    priority: 'hard',
    alphaBeta: 3,
    source: 'MSKCC / HyTEC',
    context: 'Yeniden ışınlamada >180 derece sarmasından kaçının.',
  },
  // Spinal Cord
  {
    id: 'hn-spinal-cord-sbrt-3fx',
    organ: 'Spinal Kord',
    region: 'bas-boyun',
    fractionation: 'sbrt-3fx',
    metric: 'Dmax & V14Gy',
    limit: 'Dmax < 18-20 Gy (V14Gy < 1.2 cc)',
    endpoint: 'Miyelopati',
    priority: 'hard',
    alphaBeta: 2,
    source: 'AAPM TG-101',
    context: '',
  },
  {
    id: 'hn-spinal-cord-sbrt-5fx',
    organ: 'Spinal Kord',
    region: 'bas-boyun',
    fractionation: 'sbrt-5fx',
    metric: 'Dmax & V20Gy',
    limit: 'Dmax < 23-25 Gy (V20Gy < 0.5 cc; D0.035cc < 25 Gy)',
    endpoint: 'Miyelopati',
    priority: 'hard',
    alphaBeta: 2,
    source: 'AAPM TG-101',
    context: '',
  },
  // Brainstem
  {
    id: 'hn-brainstem-sbrt-3fx',
    organ: 'Beyin Sapı',
    region: 'bas-boyun',
    fractionation: 'sbrt-3fx',
    metric: 'Dmax & V15Gy',
    limit: 'Dmax < 18-20 Gy (V15Gy < 0.5 cc)',
    endpoint: 'Nöropati / Nekroz',
    priority: 'hard',
    alphaBeta: 2,
    source: 'HyTEC Brainstem',
    context: '',
  },
  {
    id: 'hn-brainstem-sbrt-5fx',
    organ: 'Beyin Sapı',
    region: 'bas-boyun',
    fractionation: 'sbrt-5fx',
    metric: 'Dmax & V20Gy',
    limit: 'Dmax < 23-25 Gy (V20Gy < 0.5 cc)',
    endpoint: 'Nöropati / Nekroz',
    priority: 'hard',
    alphaBeta: 2,
    source: 'HyTEC Brainstem',
    context: '',
  },
  // Mandible
  {
    id: 'hn-mandible-sbrt-3fx',
    organ: 'Mandibula',
    region: 'bas-boyun',
    fractionation: 'sbrt-3fx',
    metric: 'Dmax',
    limit: 'Dmax < 26-30 Gy',
    endpoint: 'Osteoradyonekroz (ORN)',
    priority: 'soft',
    alphaBeta: 3,
    source: 'Clinical Guidelines',
    context: '',
  },
  {
    id: 'hn-mandible-sbrt-5fx',
    organ: 'Mandibula',
    region: 'bas-boyun',
    fractionation: 'sbrt-5fx',
    metric: 'Dmax & V35Gy',
    limit: 'Dmax < 35-40 Gy (V35Gy < 1 cc)',
    endpoint: 'Osteoradyonekroz (ORN)',
    priority: 'soft',
    alphaBeta: 3,
    source: 'Clinical Guidelines',
    context: '',
  },
  // Brachial Plexus
  {
    id: 'hn-brachial-sbrt-3fx',
    organ: 'Brakial Pleksus',
    region: 'bas-boyun',
    fractionation: 'sbrt-3fx',
    metric: 'Dmax',
    limit: 'Dmax < 22-24 Gy',
    endpoint: 'Brakial pleksopati',
    priority: 'soft',
    alphaBeta: 2,
    source: 'Clinical Guidelines',
    context: '',
  },
  {
    id: 'hn-brachial-sbrt-5fx',
    organ: 'Brakial Pleksus',
    region: 'bas-boyun',
    fractionation: 'sbrt-5fx',
    metric: 'Dmax & D0.035cc',
    limit: 'Dmax < 30-32 Gy (D0.035cc < 32 Gy)',
    endpoint: 'Brakial pleksopati',
    priority: 'soft',
    alphaBeta: 2,
    source: 'Clinical Guidelines',
    context: '',
  },
  // Larynx & Trachea
  {
    id: 'hn-larynx-sbrt-3fx',
    organ: 'Larenks & Trakea',
    region: 'bas-boyun',
    fractionation: 'sbrt-3fx',
    metric: 'Dmax',
    limit: 'Dmax < 28-30 Gy',
    endpoint: 'Kıkırdak nekrozu / kollaps',
    priority: 'soft',
    alphaBeta: 3,
    source: 'Clinical Guidelines',
    context: '',
  },
  {
    id: 'hn-larynx-sbrt-5fx',
    organ: 'Larenks & Trakea',
    region: 'bas-boyun',
    fractionation: 'sbrt-5fx',
    metric: 'Dmax & V35Gy',
    limit: 'Dmax < 35-40 Gy (V35Gy < 1 cc)',
    endpoint: 'Kıkırdak nekrozu / kollaps',
    priority: 'soft',
    alphaBeta: 3,
    source: 'Clinical Guidelines',
    context: '',
  },
  // Pharynx & Cervical Esophagus
  {
    id: 'hn-pharynx-sbrt-3fx',
    organ: 'Farinks & Servikal Özofagus',
    region: 'bas-boyun',
    fractionation: 'sbrt-3fx',
    metric: 'Dmax',
    limit: 'Dmax < 27-30 Gy',
    endpoint: 'Perforasyon / striktür',
    priority: 'soft',
    alphaBeta: 3,
    source: 'Clinical Guidelines',
    context: '',
  },
  {
    id: 'hn-pharynx-sbrt-5fx',
    organ: 'Farinks & Servikal Özofagus',
    region: 'bas-boyun',
    fractionation: 'sbrt-5fx',
    metric: 'Dmax & V35Gy',
    limit: 'Dmax < 35-38 Gy (V35Gy < 1 cc)',
    endpoint: 'Perforasyon / striktür',
    priority: 'soft',
    alphaBeta: 3,
    source: 'Clinical Guidelines',
    context: '',
  },
  // Skin
  {
    id: 'hn-skin-sbrt-3fx',
    organ: 'Cilt (Skin)',
    region: 'bas-boyun',
    fractionation: 'sbrt-3fx',
    metric: 'Dmax',
    limit: 'Dmax < 24-27 Gy',
    endpoint: 'Cilt ülserasyonu',
    priority: 'soft',
    alphaBeta: 3,
    source: 'Clinical Guidelines',
    context: '',
  },
  {
    id: 'hn-skin-sbrt-5fx',
    organ: 'Cilt (Skin)',
    region: 'bas-boyun',
    fractionation: 'sbrt-5fx',
    metric: 'Dmax & V35Gy',
    limit: 'Dmax < 32-35 Gy (V35Gy < 10 cc)',
    endpoint: 'Cilt ülserasyonu',
    priority: 'soft',
    alphaBeta: 3,
    source: 'Clinical Guidelines',
    context: '',
  },
`;

const regex = /\{\s*id:\s*'hn-sbrt-context'[\s\S]*?\},/;

if (regex.test(data)) {
  data = data.replace(regex, newItems);
  fs.writeFileSync('src/data/oarConstraintsData.ts', data, 'utf-8');
  console.log("Successfully replaced HN context placeholder with new constraints.");
} else {
  console.log("Could not find the placeholder to replace.");
}
